sendgrid/sendgrid-ruby

README.md

Added example and created link back to our docs page for more information on the SMTPAPI headers.

add SMTPAPI header example

---

lib/sendgrid/mail.rb

Remove two puts method-calls from mail.rb
This affects the output of the unit tests of my project.

Remove puts from mail.rb

---

.gitignore
README.md
lib/sendgrid-ruby.rb
lib/sendgrid/client.rb
lib/sendgrid/mail.rb
lib/sendgrid/recipient.rb
lib/sendgrid/template.rb
lib/sendgrid/template_mailer.rb
spec/lib/sendgrid/client_spec.rb
spec/lib/sendgrid/mail_spec.rb
spec/lib/sendgrid/recipient_spec.rb
spec/lib/sendgrid/template_mailer_spec.rb
spec/lib/sendgrid/template_spec.rb

@thinkingserious  
After https://github.com/sendgrid/sendgrid-ruby/pull/23,  I have successfully added my changes to the new version of the gem.
1. Added ability to assign a `Template` to a `Mail` object.
* If a `Mail` object has a `template` when the Mail's `to_h` method is called, it automatically adds the required template parameters to the `smtpapi` header.
2. POROs introduced to ease with Template Calling. This is an alternative way to use the Template system and is highlighted in changes to the `README`.
* `Recipient`
- Responsible for holding user data and optionally keeping track
of template substitutions.
- Has ability to add itself to an `SMTPAPI` 
* `Template`
- Responsible for keeping track of `template_id` and managing `Recipients`
- Has ability to add itself to an `SMTPAPI` …

Extend Gem with additional Template and Recipient Functionality (round 2)

---

CONTRIBUTING.md
Gemfile
sendgrid-ruby.gemspec
test/sendgrid/test_sendgrid-ruby.rb

I was unable to run all the tests b/c of this issue https://github.com/sendgrid/sendgrid-ruby/issues/71, but the two tests that did run passed. I'm letting travis take over.
See my comments on the PR on ruby-http-client for more info https://github.com/sendgrid/ruby-http-client/pull/2

remove unnecessary ruby 2.2 requirement

---

.travis.yml
test/prism.sh
test/sendgrid/test_sendgrid-ruby.rb

This change automates Prism mock server to run locally & on Travis CI before the test, & shut it down afterward according to some references provided in #109.
This should resolve #109

Automate StopLight.io Prism mock server locally & on Travis CI

---

README.md

The missing closing tag breaks markup for header "Use Cases".
Before:
After:

Add missing closing tag in README.md

---

README.md

see: https://github.com/sendgrid/sendgrid-ruby#about
Before:
After:

Fix markdown syntax to show image

---

test/sendgrid/test_sendgrid-ruby.rb

As per Node.js / Python / PHP implementations.

Typo 'user' for 'usr'

---

sendgrid-ruby.gemspec

Fixes bundler dependency issues with rails >5.0 and rack 2.0.
Solves: #159

Updated sinatra version to 2.0

---

test/sendgrid/test_sendgrid-ruby.rb

Substitute deprecated `File#exists?` with `File#exist?`. Fixes Ruby warning which was displayed in tests.

Substitute deprecated method

---

.travis.yml
gemfiles/Sinatra_1.gemfile
gemfiles/Sinatra_2.gemfile
sendgrid-ruby.gemspec

Brings back Rails 4 compatibility (and Rack 1.x applications, in general), also removes release candidate version constraint (both broken in #160). Moreover, ensures that tests are run against two major Sinatra versions, which should protect from compatibility issues in future, somewhat.
Related issue: #159.

Fixed problematic Sinatra dependency

---

sendgrid-ruby.gemspec

The keyword argument syntax that introduced Ruby 2.0 is landed on master.
Such as https://github.com/sendgrid/sendgrid-ruby/blob/v4.0.8/lib/sendgrid/client.rb#L17.

Specify required ruby version as '>= 2.0'

---

CHANGELOG.md

There was a typo in the version 5 change log.
`mail.attachment()`should be `mail.add_attachment()`

Fix add_attachment typo in changelog

---

CONTRIBUTING.md
README.md
USAGE.md
USE_CASES.md

This is a pretty small deal, but I couldn't help but notice the section links on some of the docs were using Underscore VS Hyphen. It's a pretty minor change but should boost the searchablity of some of these sections.
For reference: https://www.seomechanic.com/seo-101-hyphens-underscores-_-urls/

Making README/Doc Sections More SEO Friendly

---

.env_sample
README.md

Add a .env_sample file, update README.md

---

lib/sendgrid/helpers/mail/custom_arg.rb
test/sendgrid/helpers/mail/test_mail.rb

Sometimes the user can pass value argument in CustomArgs with a non string value. This commit will try to store whatever value comes in the form of a string.
This fixes #142

Convert key/value arguments to CustomArgs to strings

---

.codeclimate.yml
sendgrid-ruby.gemspec

Issue https://github.com/sendgrid/sendgrid-ruby/issues/247
- added .codeclimate.yml
- added robocop to development dependencies

Added .codeclimate.yml

---

sendgrid-ruby.gemspec

- Updated ruby-http-client dependency to support v3.3.0
- 

Fixes #259 Update ruby-http-client dependency to support v3.3.0

---

LICENSE.txt
examples/helpers/mail/example.rb
lib/sendgrid/helpers/mail/personalization.rb
test/sendgrid/helpers/mail/test_personalizations.rb
test/sendgrid/test_sendgrid-ruby.rb

This is an initial take on adding support for newly [added dynamic templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html).
I've added an `add_dynamic_tempalte_data` method to the `Personalization` class as well as a test and some example code to show how it would be used.
Fixes #300

Support for dynamic template data.

---

README.md

- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guide] and my PR follows them.
- [ x] I updated my branch with the master branch.
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation about the functionality in the appropriate .md file
- [ x] I have added in line documentation to the code I modified
Because `Mail` is used by Rails the "hello world" example doesn't work in the Rails console out of the box. This change fixes that and is also consistent with the existing reference to `SendGrid::API` which is also strictly speaking unnecessary if one is including this module in a class.
Perhaps there is another way to handle this but my view …

Update example to work in Rails console

---

lib/sendgrid/client.rb
test/sendgrid/test_sendgrid-ruby.rb

Resolves #270 
- It enables a `impersonate_subuser` parameter on client initialize function. When it's filled, the header `On-Behalf-Of` is added.

Add ability to impersonate subuser

---

lib/sendgrid/helpers/mail/category.rb
lib/sendgrid/helpers/stats/stats_response.rb

- Remove duplicate declaration on name variable from category.rb
- Remove unused variable from stat_response.rb.

FIX-274: Fix travis warning

---

USAGE.md
USE_CASES.md
examples/senderauthentication/senderauthentication.rb

Per the SendGrid Docs [here](https://github.com/sendgrid/docs/blob/develop/content/docs/glossary/whitelabel.md) as well as an upcoming addition to the Docs in a PR I have submitted [here](https://github.com/sendgrid/docs/pull/4182#discussion_r224903380), the term "Whitelabel" is no longer being used in SendGrid documentation and has been "deprecated" ([see here](https://github.com/sendgrid/docs/pull/4182#discussion_r224903380)), even though the API still references it. 
This PR alters the references to whitelabeling and replaces them with the following:
Whitelabel = Sender Authentication
Domain Whitelabel = Domain Authentication
IP Whitelabel = Reverse DNS
Link Whitelabel = Link branding

Remove references to "Whitelabel"

---

LICENSE.txt
USAGE.md
examples/suppression/suppression.rb
test/sendgrid/test_sendgrid-ruby.rb

Fixes #382
Updates the single spam report retrieval and deletion endpoints to be in line with the base API. https://sendgrid.com/docs/API_Reference/Web_API_v3/spam_reports.html#Get-a-specific-spam-report-GET and also updates the License dates.

[Fixes #382] Correct endpoint for single spam report requests

---

Makefile

Adding Makefile to assist with automation

---

.travis.yml

Since we have two gemfiles we are testing against, currently we will try to auto-deploy in both cases. We only need to try to deploy once.

fix: Only try to deploy once to rubygems

---

lib/sendgrid/version.rb
sendgrid-ruby.gemspec

Use latest HTTP client so that we can pass in http options.
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.
Closes #405

feat: Use latest SendGrid HTTP Client

---

README.md

I happened to click on the link, and I guess this posting is from 5 months ago 😄
~- [ ] I have added tests that prove my fix is effective or that my feature works~
~- [ ] I have added necessary documentation about the functionality in the appropriate .md file~
~- [ ] I have added in line documentation to the code I modified~
-  Removes the announcements section from the readme, since its only contents was a job posting for a job that doesn't seem to be open according to the careers page

docs: Remove announcements (the job posting is filled?)

---

Gemfile
lib/sendgrid/helpers/eventwebhook/eventwebhook.rb
sendgrid-ruby.gemspec

Fixes https://github.com/sendgrid/sendgrid-ruby/issues/426
Since we have a pretty light dependency on the starkbank implementation and it's causing issues with File operations, this change drops the dependency with minimal added code.

fix: drop the starkbank dependency

---

CHANGELOG.md
CONTRIBUTING.md
TROUBLESHOOTING.md
USAGE.md
mail_helper_v3.md

-This PR polishes the English written in the *.md files according to the grammar.ly service
- 

docs: Run all the *.md files through grammar.ly service and update accordingly

---

lib/sendgrid/helpers/mail/asm.rb
lib/sendgrid/helpers/mail/attachment.rb
lib/sendgrid/helpers/mail/bcc_settings.rb
lib/sendgrid/helpers/mail/bypass_list_management.rb
lib/sendgrid/helpers/mail/click_tracking.rb
lib/sendgrid/helpers/mail/custom_arg.rb
lib/sendgrid/helpers/mail/footer.rb
lib/sendgrid/helpers/mail/ganalytics.rb
lib/sendgrid/helpers/mail/header.rb
lib/sendgrid/helpers/mail/mail.rb
lib/sendgrid/helpers/mail/mail_settings.rb
lib/sendgrid/helpers/mail/open_tracking.rb
lib/sendgrid/helpers/mail/personalization.rb
lib/sendgrid/helpers/mail/section.rb
lib/sendgrid/helpers/mail/spam_check.rb
lib/sendgrid/helpers/mail/subscription_tracking.rb
lib/sendgrid/helpers/mail/substitution.rb
lib/sendgrid/helpers/mail/tracking_settings.rb

- Refactored classes to use ruby acessors instead of getters and setters
- Closes #326

chore: Refactor getters and setters to use ruby accessors

---

lib/sendgrid/helpers/mail/personalization.rb
test/sendgrid/helpers/mail/test_mail.rb
test/sendgrid/helpers/mail/test_personalizations.rb

fix: Checking duplicate email address specified into personalizations as case insensitive
Checking duplicate email address specified into personalizations as case insensitive

fix!: Raise error when adding duplicate email address in Personalizations

---

.rubocop.yml
lib/rack/sendgrid_webhook_verification.rb
spec/rack/sendgrid_webhook_verification_spec.rb

Fix reading position of a request body which middleware passed to an application.
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

fix: reading position of a request body

---

examples/scopes/scopes.rb
lib/sendgrid/base_interface.rb
lib/sendgrid/helpers/inbound/app.rb
lib/sendgrid/helpers/inbound/send.rb
lib/sendgrid/helpers/mail/tracking_settings.rb
lib/sendgrid/helpers/permissions/scope.rb
spec/fixtures/event_webhook.rb
spec/sendgrid/helpers/eventwebhook/eventwebhook_spec.rb
test/sendgrid/permissions/test_scopes.rb
test/sendgrid/test_sendgrid-ruby.rb

[Recent Rubocop release](https://github.com/rubocop-hq/rubocop/releases/tag/v1.1.0) identified additional styling issues. PR resolves these errors.

chore: fix rubocop styling errors

---

lib/sendgrid/helpers/mail/email.rb
test/sendgrid/helpers/mail/test_email.rb

class in constructor have definition `email: nil` but actually it can't work without "email". I think it can be confused. If I pass blank or invalid string there, it fail in `split_email` method => I suggest to raise ArgumentError with explanation instead.

fix: email is required

---

lib/sendgrid/helpers/mail/personalization.rb
test/sendgrid/helpers/mail/test_personalizations.rb

fix: Accurate duplicate checking when adding email to Personalizations

---

.rubocop_todo.yml
lib/sendgrid/base_interface.rb
lib/sendgrid/sendgrid.rb
test/sendgrid/test_sendgrid-ruby.rb

feat: Add http_options as a param in the SendGrid::API's constructor

---

.travis.yml
spec/sendgrid/helpers/settings/mail_settings_dto_spec.rb
spec/sendgrid/helpers/settings/partner_settings_dto_spec.rb
spec/sendgrid/helpers/settings/tracking_settings_dto_spec.rb
spec/sendgrid/helpers/settings/user_settings_dto_spec.rb

https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

chore: add support for ruby 3.0

---

.github/workflows/test-and-deploy.yml

Fix based on [this comment](https://github.com/sendgrid/sendgrid-ruby/pull/478#discussion_r796125502)

fix: set version env var for tests

---

examples/dataresidency/setregion.rb
lib/sendgrid/base_interface.rb
lib/sendgrid/sendgrid.rb
test/sendgrid/helpers/mail/test_data_residency.rb

feat!: Geolocation setter for sendgrid ruby
Ticket: [DII-1232](https://issues.corp.twilio.com/browse/DII-1232)

feat: geolocation setter in sendgrid-ruby for GDPR compliance
