sendgrid/sendgrid-ruby

USAGE.md
to the helper for the POST /mail/send endpoint
=> Fix broken link

lib/sendgrid/client.rb
Please see #146 for description of changes.
=> set api_key to empty string

examples/helpers/mail/example.rb
After upgrade to 5.0.0 the method `personalizations=` no longer exists.
=> Fix personalization example

TROUBLESHOOTING.md
closes #67 
@thinkingserious 
edit by @mbernier: added "closes"
=> Added Rails section and mention class collision

USE_CASES.md
Added information to `USE_CASES.md`
- How to setup a domain whitelabel 
- How to view email statistics.
- Add Whitelabel and Email Statistics to Table of Contents
This resolves issue #204 .
=> Update USE_CASES.md with Whitelabel and Email Statistics information

mail_helper_v3.md
#177 
@thinkingserious I added some of the feedback, I'm sure leaving some behind but I wanted to know if so far you are ok with the changes.
Also I have seen methods like `add_header` or `add_headers` maybe we could simplify by just having one method. What do you think?
I will wait for your feedback, so we can start coding.
=> Update mail helper v3 with feedback

TROUBLESHOOTING.md
Update the Troubleshooting Docs to demonstrate how to review the request body for debugging.
#218
=> Update Troubleshooting docs

README.md
=> Add/Update Badges on README.md

TROUBLESHOOTING.md
=> docs: Update troubleshooting section.

USAGE.md
=> Minor typo correction

lib/sendgrid/helpers/mail/email.rb, test/sendgrid/helpers/mail/test_email.rb
=> Allow users to provide rfc822 formatted email

test/sendgrid/test_sendgrid-ruby.rb
- Added unittest to check for specific repo files mentioned in #251 
=> Added unittest to check for specific repo files

LICENSE.txt
=> update LICENSE - set correct year

lib/sendgrid/helpers/mail/content.rb, lib/sendgrid/helpers/mail/email.rb, lib/sendgrid/helpers/mail/mail.rb
-  Remove getters and setters 
-  use attr_accessor instead.
=> Codebase Improvement: Use attr_accessor instead of getters and setters

TROUBLESHOOTING.md
- [ x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ x] I have read the [Contribution Guide] and my PR follows them.
- [ x] I updated my branch with the master branch.
- Fixed v3 email example broken link
=> TROUBLESHOOTING.md broken link fix

Makefile
=> Add testing to Makefile

.travis.yml
- Removed legacy HipChat connection
- Parity with twilio-ruby with respect to supported/tested versions
=> chore: Add auto-deploy to travis.yml

.travis.yml
=> fix: add skip_cleanup flag to fix travis deploy

Makefile
Bump `bundler` version number from `1.14.6` to `2.1.2` so that we can use this gem.
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.
=> Chore: bump `bundler` version to 2.1.2

sendgrid-ruby.gemspec
=> fix: loosen the ruby_http_client version constraint

docker/Dockerfile
This is just a ruby update on the Dockerfile
=> chore: Update Dockerfile ruby version

lib/sendgrid/helpers/mail/mail.rb
=> fix: tests failing on rubocop rule

examples/helpers/mail/example.rb, lib/sendgrid/helpers/mail/personalization.rb
Adds From address to personalization, as mentioned in: https://sendgrid.com/docs/for-developers/sending-email/personalizations/
=> feat: Add From address to personalization

examples/helpers/mail/example.rb, lib/sendgrid/helpers/mail/personalization.rb, test/sendgrid/helpers/mail/test_personalizations.rb, use-cases/README.md, use-cases/personalizations.md
[Internal reference](https://issues.corp.twilio.com/browse/DI-748); increments upon change already made in #466
=> feat: update tests, use-cases, examples and implementation for From personalization
